import React from "react";
import { T, CA, Btn } from "../theme/tokens.jsx";

function TermsOfServiceModal({onAccept,onDecline}){
  const [scrolled,setScrolled]=useState(false);
  const [checked,setChecked]=useState(false);
  const bodyRef=useRef(null);
  const onScroll=()=>{
    const el=bodyRef.current;
    if(!el) return;
    if(el.scrollTop+el.clientHeight>=el.scrollHeight-20) setScrolled(true);
  };
  const canAccept=scrolled&&checked;
  return(
    <div style={{position:"fixed",inset:0,background:"rgba(15,23,42,0.75)",zIndex:99999,display:"flex",alignItems:"center",justifyContent:"center",backdropFilter:"blur(4px)",fontFamily:"system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif"}}>
      <div style={{background:"#fff",borderRadius:20,boxShadow:"0 32px 80px rgba(15,23,42,0.35)",width:"min(680px,95vw)",maxHeight:"90vh",display:"flex",flexDirection:"column",overflow:"hidden"}}>

        {/* Header */}
        <div style={{background:"linear-gradient(135deg,#0f172a,#1e3a5f)",padding:"28px 32px 24px",flexShrink:0}}>
          <div style={{fontSize:11,fontWeight:700,color:"#93c5fd",textTransform:"uppercase",letterSpacing:"0.12em",marginBottom:8}}>Before You Continue</div>
          <div style={{fontSize:22,fontWeight:800,color:"#fff",letterSpacing:"-0.4px",marginBottom:4}}>Terms of Service & Privacy Policy</div>
          <div style={{fontSize:12,color:"#94a3b8"}}>CashHeap · Effective {new Date().toLocaleDateString("en-CA",{year:"numeric",month:"long",day:"numeric"})}</div>
        </div>

        {/* Scrollable body */}
        <div ref={bodyRef} onScroll={onScroll} style={{flex:1,overflowY:"auto",padding:"28px 32px",fontSize:12.5,color:"#334155",lineHeight:1.75}}>

          {[
            {h:"1. Acceptance of Terms",
             b:`By accessing or using CashHeap ("the Application"), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Application. These terms apply to all users of the Application, including users who are contributors of content or other services.`},

            {h:"2. Description of Service",
             b:`CashHeap is a personal financial management application designed to help individuals track income, expenses, bills, investments, and net worth. The Application runs locally on your device and may communicate with third-party AI services (such as Google Gemini or Ollama) when those features are enabled by the user.`},

            {h:"3. User Data & Privacy",
             b:`All financial data you enter is stored locally on your device in a SQLite database. CashHeap does not transmit your financial data to any remote server operated by the Application's developers. When AI features are used, transaction summaries or queries may be sent to third-party AI providers (Google Gemini or a local Ollama instance) solely to generate responses. You are solely responsible for the accuracy, legality, and appropriateness of all data you enter. You acknowledge that you have the right to enter any financial information you input into the Application.`},

            {h:"4. No Financial Advice",
             b:`The Application and its AI features (including the Jarvis assistant) provide informational summaries and calculations only. Nothing in the Application constitutes financial, investment, legal, or tax advice. You should consult a qualified professional before making any financial decisions. The developers of CashHeap are not liable for any financial decisions made based on information provided by the Application.`},

            {h:"5. AI-Generated Content",
             b:`Responses generated by integrated AI models (Google Gemini, Ollama, or any other configured model) are automated and may contain errors, inaccuracies, or omissions. AI-generated content is provided "as-is" without any warranty of accuracy. You agree not to rely solely on AI-generated responses for financial planning or decision-making.`},

            {h:"6. Acceptable Use",
             b:`You agree to use the Application only for lawful personal financial management purposes. You agree not to: (a) use the Application to track, conceal, or facilitate unlawful financial activity; (b) reverse-engineer, decompile, or modify the Application for malicious purposes; (c) use the Application to infringe any intellectual property rights; (d) attempt to gain unauthorised access to any systems or networks connected to the Application.`},

            {h:"7. Intellectual Property",
             b:`The Application, including its source code, design, and documentation, is the intellectual property of the developer. All rights are reserved. You are granted a limited, non-exclusive, non-transferable licence to use the Application for personal, non-commercial purposes only. You may not distribute, sell, or sublicense the Application without express written permission.`},

            {h:"8. Third-Party Services",
             b:`The Application integrates with optional third-party services including Google Gemini AI and Ollama. Your use of these services is governed by their respective terms of service and privacy policies. The developers of CashHeap are not responsible for the practices, availability, or content of third-party services. API keys you provide are stored locally on your device and are not accessible to the Application's developers.`},

            {h:"9. Disclaimer of Warranties",
             b:`The Application is provided "as is" and "as available" without warranties of any kind, express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, or non-infringement. The developers do not warrant that the Application will be uninterrupted, error-free, or free of viruses or other harmful components. You assume full responsibility for all risks associated with your use of the Application.`},

            {h:"10. Limitation of Liability",
             b:`To the fullest extent permitted by applicable law, the developers of CashHeap shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of data, loss of profits, or financial losses, arising out of or related to your use of the Application, even if advised of the possibility of such damages. In no event shall the developers' total liability exceed the amount you paid for the Application.`},

            {h:"11. Data Loss & Backups",
             b:`You are solely responsible for backing up your data. The Application stores data in a local database file. The developers are not liable for any data loss resulting from software bugs, hardware failure, accidental deletion, or any other cause. You are strongly encouraged to maintain regular backups of your database file.`},

            {h:"12. Updates & Modifications",
             b:`The developers reserve the right to modify, update, or discontinue the Application at any time without notice. These Terms of Service may be updated periodically. Continued use of the Application after any changes constitutes acceptance of the new terms. Material changes will be communicated through the Application's update notifications where possible.`},

            {h:"13. Governing Law",
             b:`These Terms of Service shall be governed by and construed in accordance with the laws of the jurisdiction in which the developer is located, without regard to its conflict of law provisions. Any disputes arising under these terms shall be subject to the exclusive jurisdiction of the courts of that jurisdiction.`},

            {h:"14. Severability",
             b:`If any provision of these Terms of Service is found to be unenforceable or invalid under applicable law, that provision shall be modified to the minimum extent necessary to make it enforceable, and the remaining provisions shall continue in full force and effect.`},

            {h:"15. Entire Agreement",
             b:`These Terms of Service constitute the entire agreement between you and the developers regarding your use of the Application and supersede all prior agreements, understandings, and representations relating to the Application.`},

            {h:"16. Contact",
             b:`If you have any questions about these Terms of Service or the Application, you may reach out through the project's GitHub repository at github.com/gchaplik/cashheap.`},
          ].map(({h,b})=>(
            <div key={h} style={{marginBottom:20}}>
              <div style={{fontSize:13,fontWeight:700,color:"#0f172a",marginBottom:6}}>{h}</div>
              <div style={{color:"#475569"}}>{b}</div>
            </div>
          ))}

          <div style={{borderTop:"1px solid #e2e8f0",paddingTop:16,marginTop:8,color:"#64748b",fontSize:11,fontStyle:"italic"}}>
            Last updated: {new Date().toLocaleDateString("en-CA",{year:"numeric",month:"long",day:"numeric"})} · CashHeap is a personal project. Use at your own discretion.
          </div>
        </div>

        {/* Footer */}
        <div style={{padding:"16px 32px 24px",borderTop:"1px solid #f1f5f9",flexShrink:0,background:"#f8fafc"}}>
          {!scrolled&&(
            <div style={{fontSize:11,color:"#94a3b8",textAlign:"center",marginBottom:12}}>
              ↓ Scroll to the bottom to enable acceptance
            </div>
          )}
          <label style={{display:"flex",alignItems:"flex-start",gap:10,marginBottom:16,cursor:"pointer",opacity:scrolled?1:0.4,pointerEvents:scrolled?"auto":"none"}}>
            <input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)} style={{marginTop:2,width:15,height:15,accentColor:"#0284C7",flexShrink:0}}/>
            <span style={{fontSize:12,color:"#334155",lineHeight:1.5}}>I have read and agree to the Terms of Service and Privacy Policy. I understand that this application provides no financial advice and I am solely responsible for my financial decisions.</span>
          </label>
          <button
            onClick={canAccept?onAccept:undefined}
            disabled={!canAccept}
            style={{width:"100%",padding:"13px",borderRadius:10,background:canAccept?"linear-gradient(135deg,#0284C7,#0369a1)":"#e2e8f0",color:canAccept?"#fff":"#94a3b8",border:"none",fontSize:14,fontWeight:800,cursor:canAccept?"pointer":"not-allowed",transition:"all .2s",letterSpacing:"0.01em",fontFamily:"inherit"}}
          >
            {canAccept?"Accept & Continue →":"Read the full terms above to continue"}
          </button>
          <button
            onClick={onDecline}
            style={{width:"100%",padding:"10px",marginTop:8,borderRadius:10,background:"transparent",color:"#94a3b8",border:"1px solid #e2e8f0",fontSize:12,fontWeight:600,cursor:"pointer",fontFamily:"inherit",transition:"all .2s"}}
            onMouseOver={e=>{e.currentTarget.style.background="#fef2f2";e.currentTarget.style.color="#ef4444";e.currentTarget.style.borderColor="#fecaca";}}
            onMouseOut={e=>{e.currentTarget.style.background="transparent";e.currentTarget.style.color="#94a3b8";e.currentTarget.style.borderColor="#e2e8f0";}}
          >
            Decline &amp; Close App
          </button>
        </div>

      </div>
    </div>
  );
}

// ── Tutorial ─────────────────────────────────────────────────────────────────

export { TermsOfServiceModal };
